### ISSUE TITLE
data_obs, data_wbgt.* are in weird format..

### ISSUE THREAD

**Issue by lisandromaders** [anacv/HeatStress#2]
Hello @anacv, 

Thanks for your contribution, is helping me a lot to understand the WBGT model and implement it. 

Am I missunderstanding something or the data files inside "data" folder are wrong?

I was trying to understand the type of radiation info one should enter in your code by looking at them, but the content of "data_obs", for example, is this:

5244 5832 0a58 0a00 0000 0200 0303 0200
0203 0000 0004 0200 0000 0100 0400 0900
0000 0864 6174 615f 6f62 7300 0003 1300
0000 0600 0003 0e00 0000 5c40 c7d6 0000
0000 0040 c7d6 8000 0000 0040 c7d7 0000
0000 0040 c7d7 8000 0000 0040 c7d8 0000
0000 0040 c7d8 8000 0000 0040 c7d9 0000
.......

Should it be like this? 

Thanks in advance for any reply! 

Regards, Lisandro

**Comment by anacv** [comment]
Dear @lisandromaders,

Thanks for your interest in the package! 
I do not know how you got to that weird format, I am not able to replicate it. Each dataset is an R data frame containing several variables/outputs (time series of daily values for summer 2003). See:

```
library(HeatStress)
data(data_obs)
str(data_obs)
```
This should give you:

```
'data.frame':	92 obs. of  6 variables:
 $ Dates  : Date, format: "2003-06-01" "2003-06-02" "2003-06-03" ...
 $ tasmean: num  19.4 19.6 17.8 17.6 19.1 20.7 22.6 22.8 21.8 21.2 ...
 $ dewp   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hurs   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ wind   : num  1.4 2.2 1.7 2.2 0.6 0.6 1.7 1.4 1.7 1.4 ...
 $ solar  : num  271 281 312 283 NA NA 352 350 343 336 ...
```

And for the WBGTsun:
```
data(data_wbgt.Liljegren)
str(data_wbgt.Liljegren)
```

This should give you:

```
List of 3
 $ data: num [1:92] NA NA NA NA NA NA NA NA NA NA ...
 $ Tnwb: num [1:92] NA NA NA NA NA NA NA NA NA NA ...
 $ Tg  : num [1:92] NA NA NA NA NA NA NA NA NA NA ...
```

See the help pages to interpret the output. Note that there are NAs at the begining due to some missing values in relative humidity right at the begining of this little series.

The type of radiation is solar surface downwelling shortwave radiation in W/m2.
I hope this helps.

Ana

**Comment by lisandromaders** [comment]
Hi Ana, 

thaks for your quick reply!

Maybe it's my bad. I am not using R language, I am writting a C++ code of the WBGT standard.

I tried to open the "data_*" files using a text editor, but I think this is a R structure, right? Probably if I try to open like you suggested

```
library(HeatStress)
data(data_obs)
str(data_obs)
```

it might work. I wil give it a try and will let you know!!

**Comment by anacv** [comment]
This is an R package and .rda files and data frames are R-specific. To use it you will need to use R. 
Best.
Ana
